---
abstract: 'Install all the CPAN modules needed by Cabinet'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Cabinet
no_index:
  directory:
    - t
    - xt
    - eg
    - examples
    - corpus
  namespace:
    - t::lib
  package:
    - DB
provides:
  Task::Cabinet:
    file: lib/Task/Cabinet.pm
    version: 0.09
requires:
  Bundle::PlRPC: 0
  Carp: 0
  DBI: 0
  Dancer: 0
  Dancer::Debug: 0
  Dancer::Plugin::Database: 0
  Dancer::Plugin::Redis: 0
  Dancer::Session::Redis: 0
  Digest::MurmurHash: 0
  JSON: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Net::CIDR::Lite: 0
  Plack: 0
  Plack::Middleware::Debug: 0
  Plack::Middleware::Debug::DBIProfile: 0
  Plack::Middleware::Debug::Redis: 0
  Starman: 0
  Template: 0
  Template::Plugin::Octets: 0
  Text::MicroTemplate: 0
  Time::HiRes: 0
  Try::Tiny: 0
  WWW::Mechanize: 0
  YAML: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/Wu-Wu/Task-Cabinet/issues
  homepage: https://metacpan.org/release/Task-Cabinet
  repository: git://github.com/Wu-Wu/Task-Cabinet.git
version: 0.09
x_authority: cpan:CHIM
